version: '2.1'

services:
  db:
    image: mysql
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sam
      MYSQL_USER: tester
      MYSQL_PASSWORD: test
      MYSQL_PORT: 3306
    container_name: db_test
    ports:
      - "3306:3306"
    tty: true

