version: '2.1'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge_lalamove
      MYSQL_USER: tester
      MYSQL_PASSWORD: test
      MYSQL_PORT: 3306
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  api:
    image: api
    build:
      context: ./Go
    volumes:
      - "./Go:/go"
    container_name: api
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db